### ISSUE TITLE
Blank UI elements on Linux.

### ISSUE THREAD

**Issue by orcololo** [ValveSoftware/Dota-Underlords#11]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/orcololo/3a642e1133fc718f7362bd14ef1eb6ff
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

Well, i'm having some issues on linux with blank boxes on the UI. :(
https://imgur.com/SHXbEEe <-- Screenshot.

#### Steps for reproducing this issue:

1. Launch Steam
2. Launch Dota Underlords
3. Get blank boxes

**Comment by danginsburg** [comment]
Can you try dropping to a terminal and posting the output of doing something like this:

```~/.steam/steam/steamapps/common/Underlords/game$ ~/.steam/steam/ubuntu12_32/steam-runtime/run.sh ./underlords.sh -con_logfile```

Also posting game/dac/console.log may be useful.

It looks like you're missing fonts.

**Comment by orcololo** [comment]
When I try to run `~/.steam/steam/steamapps/common/Underlords/game$ ~/.steam/steam/ubuntu12_32/steam-runtime/run.sh ./underlords.sh` -con_logfile, it says that `~/.steam/steam/ubuntu12_32/steam-runtime/run.sh` doesn't exist.

game/dac/console.log:
https://gist.github.com/orcololo/a9c1377a0e0434db7f76f0b1780b657c

**Comment by danginsburg** [comment]
Hmm...console.log doesn't have any clues that I see, but it won't show failures to load .so files.  Well, you may just be able to run underlords.sh directly.  If not, find wherever your steam folder is and you should have run.sh (something like find ~/.steam/steam/ -iname "run.sh").

**Comment by orcololo** [comment]
Got it to work switching to arch, looks like it was some outdated driver issue...but now game runs at -30fps. :(

**Comment by jenqaz** [comment]
Hi!
I have the same issue. Here's my config.log and settings

[Steam settings](https://gist.github.com/jenqaz/c7458d9a7a9aa488f2b98c5bc87ff648)
[Console.log](https://gist.github.com/jenqaz/68f02f871aee14cf3b8ab5564e9e0f13)
[Screenshot](https://imgur.com/GGvHXmz)

**Comment by orcololo** [comment]
Hey, @jenqaz have you tried updating intel graphics driver via oibaf's ppa? This solved my problem while using ubuntu 19.04

**Comment by kisak-valve** [comment]
Ivybridge and Haswell does not have hardware support for texture swizzles and needs a mesa build with https://cgit.freedesktop.org/mesa/mesa/commit/?id=d2aa65eb1892f7b300ac24560f9dbda6b600b5a7 for the Source 2 engine to render properly with Vulkan.

This is unrelated to the issue you encountered @orcololo.

**Comment by jenqaz** [comment]
Thanks a lot @orcololo `sudo add-apt-repository ppa:oibaf/graphics-drivers` solved the problem!

**Comment by NickCageNick** [comment]
Hello Friends! I have the same problem in Manjaro/Arch Linux
Someone here have any idea what is happening?
Otherwise some ppl in Reddit are talking about the same error in Dota 2 but I don't find any solution with this.
The old issue in Dota 2 is about one lib in Steam/steamapps/common/Underlords/game/bin/linuxsteamrt64/ called 'libpango.so' this specific solution doesn't work but I think the solution is with these libs
[The same issue in Dota 2](https://github.com/ValveSoftware/Dota-2/issues/1195)
[reddit link](https://www.reddit.com/r/underlords/comments/c2p7ye/recently_installed_game_on_linux_all_ui_elements/)
[My system informations](https://gist.github.com/NickCageNick/3f8ffd1188df582c759442a4a46e4901)
[The output of: "steam steam://rungameid/1046930"](https://gist.github.com/NickCageNick/6771bfa8501a52f86a4f48727b8b718a)

**Comment by kisak-valve** [comment]
Hello @NickCageNick, you have the same issue that @jenqaz had. Mesa 19.0.6 is too old for this game and Intel Ivybridge. Please update to mesa 19.1.0 (or newer).

**Comment by nicolas-oliveira** [comment]
@kisak-valve Thanks for the answer, setting the system to branch testing solve the problem in Manjaro.
sudo pacman-mirrors --api --set-branch testing
sudo pacman-mirrors --fasttrack 5 && sudo pacman -Syyu

**Comment by ykvch** [comment]
My terminal log shows during launch: https://gist.github.com/ykvch/71d82c475ac6d83853d14277ba494e03
Maybe that'd be helpful (archlinux).

**Comment by ykvch** [comment]
There 2 PCs running manjaro linux (both have mesa 19.0.6), very similar, but only one of them shows blanks instead of text.
Possibly some log-diffs could help investigating?
So far the only seemingly important diff-message on host with issue (mesa 19.0.6):
`INTEL-MESA: warning: Ivy Bridge Vulkan support is incomplete`

upd.: `mesa` package upgrade 19.0.6 -> 19.1.1 indeed helped to fix the issue.

**Comment by gdrewb-valve** [comment]
This issue appears to be resolved by the various driver and system updates mentioned.
