### ISSUE TITLE
Desktop-friendly Fullscreen causes LOD flashing

### ISSUE THREAD

**Issue by IceAmaura** [ValveSoftware/Dota-Underlords#27]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/IceAmaura/6cf93493d7a561afb5e0772d4848c93f
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible: 

Low quality textures appear in the menu and LODs flash in game from high to low quality rapidly, as well as textures seeming to disappear entirely sometimes.
Demonstration: [https://youtu.be/lBQZ2TlOOes](https://youtu.be/lBQZ2TlOOes)
Note that this only happens in GNOME, and in KDE the issue doesn't exist as far as I've tested. Windowed and Borderless Windowed work in GNOME as well without the issue.
Another note is I have an NVIDIA Optimus system and I'm using the NVIDIA GPU, as well as the proprietary driver.

#### Steps for reproducing this issue:

1. Use GNOME
2. Launch Underlords and start a game
3. Wait for flickering to start

**Comment by kisak-valve** [comment]
Hello @IceAmaura, can you check if your gnome session is running with X or wayland? If it's gnome/wayland, can you check if gnome/X is also affected?

**Comment by IceAmaura** [comment]
Checking XDG_SESSION_TYPE does show Gnome is on X11, not on Wayland.

**Comment by danginsburg** [comment]
Can you run with -con_logfile and upload the log?  My best guess is that VK_KHR_memory_budget is returning small values for amount of remaining GPU memory and we are constantly thrashing with the texture streamer.  You may get better results by lowering the texture quality in the video settings since it will put less pressure on GPU memory.  I don't know why there would be a difference in KDE vs GNOME unless it's just a case of how much GPU memory the desktop environment is using.

**Comment by IceAmaura** [comment]
Hi Dan,

I did some more extensive testing last night and was going to write it up
this morning, but you are correct on the video memory per DE theory. The
issue does happen on KDE, just much later than Gnome, where the issue is
apparent immediately. Lowering textures did nearly resolve the issue but
still had light flickering. When I get access to the PC I'll get back to
you with that log.

**Comment by IceAmaura** [comment]
[Here](https://gist.github.com/IceAmaura/b7c9eac81056f5cfe1c49a344823bfcc) is the gist of the log. As predicted there's a ton of extremely low memory errors.

**Comment by danginsburg** [comment]
Thanks @IceAmaura - so it looks like VK_EXT_memory_budget is giving us 690MB of GPU memory to work with.  The texture streamer starts reducing the texture pool size once we reach 80% of the budget as a heuristic.  This pushes the pool size all the way down to 300MB and starts thrashing.  

I will look into seeing if I can improve the texture streaming behavior in this scenario.

**Comment by danginsburg** [comment]
Also, for now, you could try adding -vulkan_disable_ext_memory_budget to your Launch Options.  This will set the pool size based on GPU memory on the device rather than what is available.  Unfortunately, you may hit crashes instead of thrashing if we fail GPU memory allocations, but if everything fits it may behave OK.  I'd also suggest turning your texture quality down to the lowest settings.

**Comment by IceAmaura** [comment]
Alright. In case anyone else comes along with the same issue, I measured
VRAM usage and KDE uses significantly less, so if I want to play Underlords
I restart my PC to flush the VRAM and switch to KDE to play for now.

**Comment by danginsburg** [comment]
I'm going to close out this bug because I believe the underlying behavior when memory gets low has been fixed.  If you see it happen again with the latest build of Underlords please let me know and provide console log.
