### ISSUE TITLE
I'm a noob trying to run dota underlords in my ubuntu 16.04

### ISSUE THREAD

**Issue by tupiniking** [ValveSoftware/Dota-Underlords#28]
I downloaded the game and when i run a get this error:
------------------------------------------------------------------------------------------------------------x----
Error

CreateSWapChain():
The selected graphics queue does not support presenting a swapchain image.
So i started searching the internet and found out that this is somehow related to the direct rendering of my graphic card, it isn't enable or updated, i guesss....

So, i've done a series of updating and stuff, updated the nvidia drivers, the intel drivers, and the vulkan thing that it's required to run stuff on ubuntu....

Then i realized that my graphic card is intel:

00:02.0 VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07) (prog-if 00 [VGA controller])
DeviceName: Onboard IGD
Subsystem: Dell Device 0829
Flags: bus master, fast devsel, latency 0, IRQ 280
Memory at dd000000 (64-bit, non-prefetchable) [size=16M]
Memory at b0000000 (64-bit, prefetchable) [size=256M]
I/O ports at f000 [size=64]
Expansion ROM at [disabled]
Capabilities: 
Kernel driver in use: i915_bpo
Kernel modules: i915_bpo

and my 3d controller is nvidia related:

01:00.0 3D controller: NVIDIA Corporation GP108M [GeForce MX150] (rev a1)
Subsystem: Dell Device 0829
Flags: bus master, fast devsel, latency 0, IRQ 16
Memory at de000000 (32-bit, non-prefetchable) [size=16M]
Memory at c0000000 (64-bit, prefetchable) [size=256M]
Memory at d0000000 (64-bit, prefetchable) [size=32M]
I/O ports at e000 [size=128]
Expansion ROM at df000000 [disabled] [size=512K]
Capabilities: 
Kernel driver in use: nvidia
Kernel modules: nvidiafb, nouveau, nvidia_430_drm, nvidia_430

when i run vulkaninfo | less it gives me the same error as resolved in this commentary:
#131

and still, i don't know if this solve is exclusive to nvidia graphic cards, or if it apllies to my issue.

I've created a Frankenstein, since i don't know much about ubuntu, nor graphic cards and such, and had a lot of free time, maybe i've disposed some irrelevant information here... so, if u are interested in helping me, i'd be very greatful. THank you in advance...

**Comment by tupiniking** [comment]
the #131 commentary is actually this one:
https://github.com/mit-fast/FlightGoggles/issues/131

**Comment by kisak-valve** [comment]
Hello @tupiniking, this sounds similar to https://github.com/ValveSoftware/Dota-Underlords/issues/26#issuecomment-512963679 except you appear to be using an nvidia optimus laptop. There's a good chance X needs to be configured to use DRI3 to use Intel's Vulkan driver or look into using [primus_vk](https://github.com/felixdoerre/primus_vk) to get the nVidia driver to render to the screen.

**Comment by tupiniking** [comment]
![Screenshot from 2019-07-26 21-00-59](https://user-images.githubusercontent.com/53354094/61987901-9050d200-afe8-11e9-94fa-2d58e6b9622f.png)

**Comment by tupiniking** [comment]
i can't seem to find the correct file to change the text to DRI 3, i actually searched it a lot yesterday

**Comment by tupiniking** [comment]
![Screenshot from 2019-07-26 21-03-43](https://user-images.githubusercontent.com/53354094/61987928-e6257a00-afe8-11e9-865d-ca31e8c6de9e.png)

**Comment by Muffindrake** [comment]
Hello, I'm using a (more recent) nvidia optimus laptop, and I have already configured it such that everything is rendered on the nvidia card, where the intel card serves only to display the already-rendered frames. This using nvidia's built-in "support" called PRIME, which is presently the only official way to make full use of your dedicated card on such a system, which stays turned on as long as the X11 session is running, unlike the power savings that the full switching solution under Windows provides, but there's politics in the way.

I use the following utility to manage a separate X11 configuration using the nvidia card https://github.com/Witko/nvidia-xrun

That being said, Dota 2 and Underlords will immediately segmentation fault if a launch is attempted in Vulkan mode (Dota 2 has the workaround in using OpenGL instead). This is unfortunate, because `vulkaninfo` will output the correct information targeting my nvidia card, as well as `vkcube` running correctly.

Well, that, and just about any other `native Vulkan application`, a media player such as mpv running perfectly fine, or, say, `League Of Legends`, their gamemode TFT and any other DX9-using title, running perfectly fine through D9VK. It's hilariously funny that the supposed native Vulkan application won't run (**only** limited to the aforementioned two Source titles by Valve), but the thing behind five compatibility layers will.

standard output/error: https://gist.githubusercontent.com/Muffindrake/98fe62b7a96a07d538c0aaa3c1d5d94c/raw/bd89b0321cde348268c4ed1414f622b2a17bc90e/underlords.log

crash dump: https://mega.nz/#!RCo13aob!OcUY4NZMf1Gi-996LU6frrAlFvAgrbdgREfe-ZhXG-Q

Thank you for your assistance.

**Comment by Muffindrake** [comment]
Underlords seems to launch properly for me as of the current version (build 231). I am not sure if a driver update fixed that (I am now on nvidia-drivers version 435.17) or there was a code change, but in any case, thank you.

**Comment by gdrewb-valve** [comment]
@tupiniking, were you able to get things working?  Can this issue be closed?

**Comment by gdrewb-valve** [comment]
Closing pending feedback.
